### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by KrumpetPirate** [paladini/aax2mp3-easy#1]
Found your repo by checking the referral links in my repo to your (??) blog. Not a bad implementation and makes it much easier to use overall. I am, however, concerned by a few things:

1. #!/bin/bash shebang could break on some systems that don't use standard bash location (some distros of Linux do this for some reason). #!/usr/bin/env bash would be better here
2. Consider adding checks for pip, wget, and ffmpeg. My repo now automatically checks ffmpeg installation thanks to work done by [danielhoherd](https://github.com/danielhoherd) so that can be used to check style for the script. I don't know if libmp3lame is also needed, it is used in mp3 conversion in my script.
3. You should trap ctrl+c and exit the script altogether if encountered, again danielhoherd did this for AAXtoMP3.
4. Consider adding checks to make sure the repos were successfully extracted using wget. That chromedriver site crashed a few times while I was attempting to figure out the ffmpeg stuff for AAXtoMP3 so that is a potential weak point.

All that being said, do I have your permission to link your project in my README markdown? I think it could be useful for newer users. I don't anticipate many github Linux users that are attempting to decode an Audible file to fall into that category but you can never be sure.

**Comment by KrumpetPirate** [comment]
Additionally it has been suggested to me that a sideloaded .authcode file present in the working directory should override the passed arguments. I have not had a chance to implement this yet, but perhaps a check in your script for such a file before running the audible-activation stuff could be useful. This would certainly make it easier to capture batch calls without having to register for the authcode and remove it every time which the audible-activation guy said was a serious problem if the de-activation failed.

**Comment by paladini** [comment]
Hello @KrumpetPirate , sorry for the (very) late reply.  Thanks for your suggestions, all of them would be very useful for this script.

Right now I don't have an Audible account for testing purposes and that detail break my willings to improve this script at this moment. Anyway, I would like to improve it ASAP and your suggestions will guide me throughout this improvements. **One important question I would like to ask you before start to develop these suggestions is:** are you willing to make your script easier to use, like providing (in the future) a friendly GUI? What's the long-term goals for AAXtoMP3?

Also, are you still interested in adding a reference for this script in your README? If so, of course you have permission - don't need to ask ;)

**Comment by KrumpetPirate** [comment]
Nope, I have no intention of making a GUI for the script as it really is just a frontend for FFMPEG. I am only really interested in providing an easier way for users that don't have access to an Audible official application or don't want to use the official app for some reason. The script has changed since I originally opened this and I think it accomplishes the goals that I set out.
