### ISSUE TITLE
audible has changed the sign-in process

### ISSUE THREAD

**Issue by ndanieley** [paladini/aax2mp3-easy#18]
looks like audible is now requiring Capta or some such extra level after name/password; is there any way to handle that?

**Comment by FooBarTrixibell** [comment]
![Screenshot from 2019-05-02 08-36-54](https://user-images.githubusercontent.com/13545093/57041687-f6161200-6cb6-11e9-92a1-a3f0b8a97aa5.png)
I can confirm this is an issue, but only after converting ~8 books in a row.

**Comment by vanson44** [comment]
Hello,

You need to activate the debug mode of audible-activator in the script.

For it, add -d option line 74 like that :

`ACTIVATION=$(python audible-activator-feature_login_as_arg/audible-activator.py -d --user $LOGIN --password $PASSWORD | tail -1)`

Or use use the fork I created : https://github.com/vanson44/aax2mp3-easy/tree/patch-1

Have a nice day :D

**Comment by paladini** [comment]
The pull request was accepted right now, so this problem should not happen anymore. 

PR: #20 

Thanks, @vanson44 !!
