### ISSUE TITLE
AAXtoMP3.sh called by aax2mp3_easy.sh but the name is AAXtoMP3 

### ISSUE THREAD

**Issue by chrplr** [paladini/aax2mp3-easy#2]
The script crashed with the following error message:

     bash: AAXtoMP3-master/AAXtoMP3.sh: No such file or directory

Solution:

    mv AAXtoMP3-master/AAXtoMP3 AAXtoMP3-master/AAXtoMP3.sh

-----------------
Now the script stops with the message

    2017-07-05 22:54:14+0200 Decoding Player with auth code [*]...

but no mp3 is created. I am investigating.

**Comment by chrplr** [comment]
Ok, the previous error 

2017-07-05 22:54:14+0200 Decoding Player with auth code [*]...

was due to a crash of selenium:

    File "/home/cp983411/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: session not created exception: Chrome version must be >= 58.0.3029.0
    (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.9.8-040908-generic x86_64)

solved by updating google-chrome to version 61.xxx

**Comment by chrplr** [comment]
Now, my files are .aa rather then .aax

I try to replace `-activation_bytes` by `-aa_fixed_key` in the ffmpeg command line, but to no avail :-(

I get the message :

   [aa @ 0x23eb6a0] aa_fixed_key value needs to be 16 bytes!

(the author_code obtained from the web site is only 4 bytes)

**Comment by paladini** [comment]
@chrplr , do you still need some help with that? Have you solved it or still with the same issue?

Thanks for issuing this bug!

**Comment by paladini** [comment]
Since this issue was not updated for a while and the author didn't give more news on that matter, I'm closing this issue. If you got the same problem, please comment this Issue and I'll reopen it.
