### ISSUE TITLE
audiobooks not there

### ISSUE THREAD

**Issue by ghost** [paladini/aax2mp3-easy#7]
hi ther i have a small problem after the conversion i cant find the audiobook file anywhere i cant find my completed file after conversion thnk you

**Comment by erseco** [comment]
You must install ffmpeg, if you are on debian/ubuntu please run `sudo apt-get install ffmpeg`

**Comment by paladini** [comment]
I'll add this prerequisite to project's readme, thanks for the answer and for the tip, @erseco . This solved your issue, @ghost ?

**Comment by paladini** [comment]
@ghost account seems to be deleted. I'll close the issue.
